# Generated by Django 2.1.4 on 2019-02-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'brief_description')},
        ),
    ]
