# Generated by Django 2.1.4 on 2019-01-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='brief_desctiption',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='brief_desctiption',
            new_name='brief_description',
        ),
    ]
